"""Create pipeline_runs table

Revision ID: 4dda85330931
Revises: 
Create Date: 2026-09-13 16:31:58.893821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dda85330931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('documents_discovered', sa.Integer(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('documents_skipped', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('total_embedding_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
